# Generated by Django 4.0.3 on 2022-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
